### ISSUE TITLE
sphinx: replace AEZ with Lioness?

### ISSUE THREAD

**Issue by david415** [Katzenpost/core#12]
Quantum Key-Recovery on full AEZ
https://eprint.iacr.org/2017/767.pdf

Should we use Lioness instead?

**Comment by Yawning** [comment]
No.  

> A more conservative approach would be to change a bit the way the associated data is processed. 

We don't process any AD.  Also quantum adversaries are beyond the threat model.

**Comment by Yawning** [comment]
Rethought it.  Still a nope.
