### ISSUE TITLE
Implement the wire protocol.

### ISSUE THREAD

**Issue by Yawning** [Katzenpost/core#3]
Everyone needs to be able to talk to each other.

**Comment by david415** [comment]
- [ ] implement high level API for receiving wire protocol command structures
- [ ] implement encryption scheme for retreive_message and message commands AND update the wire protocol specification
- [ ] code review from @Yawning

**Comment by Yawning** [comment]
Calling this done as of 82ad0aedd2c0f83cd3228270578427ccb1456b76
