### ISSUE TITLE
wire: Add commands for retrieving cached PKI consensus files

### ISSUE THREAD

**Issue by david415** [katzenpost/core#32]
Clients can get the PKI consensus files directly from their Provider via an additional wire protocol command, GET_CONSENSUS... and the response command CONSENSUS. The current PKI specification draft includes more details: https://github.com/katzenpost/docs/blob/master/specs/pki.txt

**Comment by david415** [comment]
new pr: https://github.com/katzenpost/core/pull/35

**Comment by Yawning** [comment]
Fixed.

5c7649a1f2ed2073057d8a3f57560122fb4bb7d5
fc71b4f21bd1b43a8ec46e2bd810a4c61343d63a
