### ISSUE TITLE
should the server calculate clock skew as well?

### ISSUE THREAD

**Issue by david415** [katzenpost/core#60]
to what end? should the server just log it or wtf.

client currently sends ad struct with nil unix_time field:
https://github.com/katzenpost/core/blob/master/wire/session.go#L220

server currently ignores unix_time field of ad struct:
https://github.com/katzenpost/core/blob/master/wire/session.go#L271

**Comment by mixmasala** [comment]
The clients should not submit information about their clocks.

**Comment by david415** [comment]
ok :+1:
