### ISSUE TITLE
Sphinx padding bug

### ISSUE THREAD

**Issue by david415** [katzenpost/core#92]
According to the recently submitted paper: Breaking and (Partially) Fixing Provably Secure Onion Routing, ( https://arxiv.org/abs/1910.13772 ) there is a padding bug where a sphinx implementation creates a header and in so doing uses zeros to pad the beta field whereas random data should be used instead because of the use of the stream cipher...

https://github.com/UCL-InfoSec/sphinx/blob/c05b7034eaffd8f98454e0619b0b1548a9fa0f42/SphinxClient.py#L67

    # The os.urandom used to be a string of 0x00 bytes, but that's wrong
    beta = dest + id + os.urandom(((2 * (p.r - nu) + 2)*p.k - len(dest)))
    beta = p.xor(beta,
	p.rho(p.hrho(asbtuples[nu-1]['s']))[:(2*(p.r-nu)+3)*p.k]) + phi

This bug, that is, if beta were padded with zeros instead of random bytes would allow
an adversary to determine the length of the route. Similarly, in the Katzenpost Sphinx it looks like Beta is zero padded... but only for the cases where fewer than the max number of hops is used.  Minclient always creates Sphinx packets with the maximum number of hops and thus is not affected by this bug. Katzenpost mix servers send mix loops and these have shorter than maximum path lengths... and thus would be affected by this bug.

**Comment by burdges** [comment]
Actually I do not understand the attack right now, even in the provider case, contrary to my comment in https://github.com/sphinx-cryptography/rust-sphinxcrypto/issues/6.   

We assume that the stream cipher output form the key exchange rho is every bit as random as the system randomness (ROM), so adding this randomness cannot improve security unless you must reveal the stream cipher output, probably by revealing the seed, but afaik you've no reason to do so even in a provider model.

**Comment by burdges** [comment]
Nice!  I've the same bug in my code actually:  https://github.com/burdges/lake/blob/master/Xolotl/src/sphinx/client.rs#L709
