### ISSUE TITLE
incorrect-looking // +build line

### ISSUE THREAD

**Issue by rsc** [katzenpost/core#97]
I've been analyzing `// +build` usage in the Go ecosystem and turned up [monotime/monotime_linux_generic.go](https://github.com/katzenpost/core/blob/e6fb1c2b53cf7971479ad40cde8e71ea7728955e/monotime/monotime_linux_generic.go), which says:

```
// +build linux,!amd64
// +build linux,amd64,noasm
// +build !go1.9
```

This means "(linux && !amd64) && (linux && amd64 && noasm) && !go1.9",
which is unsatisfiable since !amd64 and amd64 cannot both be true.

From context it looks like the intent was to OR those three lines together, which would be:

    // +build linux,!amd64 linux,amd64,noasm !go1.9

Best,
Russ

**Comment by muesli** [comment]
I agree, that definitely looks fishy. Thanks for the heads up @rsc!

We should also check the build tags of the other implementations, since we obviously can only have one of them active at a time.

**Comment by david415** [comment]
@rsc thanks!
